### PR TITLE
feat: use a good library

### PR DESCRIPTION
**Pull request by goverfl0w**
this uses good code!

### CODE REVIEW

**Review by arHSM — APPROVED** [review]

**Comment by goverfl0w** [comment]
This LGTM! 👍🏼

**Comment by promise** [comment]
idk python but looks like a lot of code so lgtm

**Review by arHSM — APPROVED** [review]
LGTM

**Comment by goverfl0w** [comment]
@yonilerner please review! i haven't seen activity in 3 seconds!!! 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡

**Comment by yonilerner** [comment]
Closed in favor of https://github.com/yonilerner/yonebot/pull/2

**Pull request closed without merging**
